### ISSUE TITLE
Do not remove payloads still referred to by other entries when prefix pruning

### ISSUE THREAD

**Issue by sgwilym** [earthstar-project/willow-js#10]
Currently when an entry is prefix pruned its corresponding payload is removed regardless of whether any remaining entries still refer to that payload via the same payload digest.

**Comment by AljoschaMeyer** [comment]
What does it mean for "an entry to refer to a payload"? There is no such concept in Willow.

**Comment by sgwilym** [comment]
Updated for clarity. :) 

(I hope)
